name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish devcontainer features
        uses: devcontainers/action@v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
          devcontainer-cli-version: "0.83.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
