name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # npm install -g @devcontainers/cli
      # devcontainer features publish ./src --namespace ghcr.io/ronniestafford
      # devcontainer features publish -r ghcr.io -n ronniestafford/devcontainers ./src
      - name: Publish devcontainer features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
