name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Generate feature docs
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          base-path-to-features: "./src"

      - name: Commit release
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git add .
          git commit -m "chore(release): v$VERSION"

      - name: Create tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a v$VERSION -m "Release v$VERSION"

      - name: Push commit and tag to origin
        run: git push origin main --follow-tags
