name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate feature docs
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          base-path-to-features: "./src"

      - name: Update feature versions
        run: |
          find ./src -name devcontainer-feature.json -print0 | while IFS= read -r -d '' FILE; do
            jq ".version = \"$VERSION\"" "$FILE" > tmp.$$.json
            mv tmp.$$.json "$FILE"
          done
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Commit release
        run: |
          git add package.json package-lock.json $(find ./src -name devcontainer-feature.json)
          git commit -m "chore(release): v$VERSION"
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Create annotated tag
        run: |
          git tag -a "v$VERSION" -m "Release v$VERSION"
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Debug tags
        run: |
          git tag
          git show-ref --tags

      - name: Push changes
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true
